spring:
  application:
    name: task-manager

    #H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password:

    # H2 Console(view the database)
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
